//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


//model generowany za pomoca Entity Framework - z mojej istniejacej bazy
namespace Cytaty.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CytatyConnection : DbContext
    {
        public CytatyConnection()
            : base("name=CytatyConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cytaty> Cytaty { get; set; }
        public virtual DbSet<Mysliciele> Mysliciele { get; set; }
        public virtual DbSet<SlowaKluczoweWCytatach> SlowaKluczoweWCytatach { get; set; }
        public virtual DbSet<SłowaKluczowe> SłowaKluczowe { get; set; }
        public virtual DbSet<Utwory> Utwory { get; set; }
    }
}
