//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cytaty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mysliciele
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mysliciele()
        {
            this.Cytaty = new HashSet<Cytaty>();
            this.Utwory = new HashSet<Utwory>();
        }
    
        public int ID_Mysliciel { get; set; }
        public string Mysliciel { get; set; }
        public string Lata_życia { get; set; }
        public string Biogram { get; set; }
        public Nullable<System.DateTime> DataDodania { get; set; }
        public Nullable<System.DateTime> DataEdycji { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cytaty> Cytaty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utwory> Utwory { get; set; }
    }
}
