//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cytaty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlowaKluczoweWCytatach
    {
        public int ID { get; set; }
        public int ID_Cytat { get; set; }
        public int ID_SlowoKlucz { get; set; }
    
        public virtual Cytaty Cytaty { get; set; }
        public virtual SłowaKluczowe SłowaKluczowe { get; set; }
    }
}
