//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cytaty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utwory
    {
        public int ID_Utwor { get; set; }
        public string Tytuł { get; set; }
        public Nullable<int> RokWydania { get; set; }
        public Nullable<int> ID_Mysliciel { get; set; }
    
        public virtual Mysliciele Mysliciele { get; set; }
    }
}
